name = input('Введите имя: ')
surname = input('Введите фамилию: ')
print('Вас зовут')
print(name)
print(surname)

name = input('Введите имя: ')
surname = input('Введите фамилию: ')
location = input('Введите город проживания: ')
print('==========')
print('Вас зовут', name, surname)
print('Вы живёте в городе', location)
